-- Admin Structure SQL Setup

ALTER TABLE k_users 
  ADD COLUMN IF NOT EXISTS role ENUM('user','admin') DEFAULT 'user',
  ADD COLUMN IF NOT EXISTS kredi INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_banned TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL;

CREATE TABLE IF NOT EXISTS k_credits_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid INT NOT NULL,
  delta INT NOT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  admin_id INT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX(uid),
  INDEX(admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS k_announcements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  author VARCHAR(100) DEFAULT 'system',
  visible TINYINT(1) DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS k_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid INT DEFAULT NULL,
  ip VARCHAR(64) DEFAULT NULL,
  country_name VARCHAR(64) DEFAULT NULL,
  country_code VARCHAR(8) DEFAULT NULL,
  city VARCHAR(64) DEFAULT NULL,
  region VARCHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Optional: Make user #1 admin if exists
UPDATE k_users SET role='admin' WHERE id=1;
